# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import producto_pb2 as producto__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in producto_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductoServiceStub(object):
    """El servicio que define las funciones remotas
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngresarProducto = channel.unary_unary(
                '/producto.ProductoService/IngresarProducto',
                request_serializer=producto__pb2.ProductoRequest.SerializeToString,
                response_deserializer=producto__pb2.ProductoResponse.FromString,
                _registered_method=True)


class ProductoServiceServicer(object):
    """El servicio que define las funciones remotas
    """

    def IngresarProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngresarProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.IngresarProducto,
                    request_deserializer=producto__pb2.ProductoRequest.FromString,
                    response_serializer=producto__pb2.ProductoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'producto.ProductoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('producto.ProductoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductoService(object):
    """El servicio que define las funciones remotas
    """

    @staticmethod
    def IngresarProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/producto.ProductoService/IngresarProducto',
            producto__pb2.ProductoRequest.SerializeToString,
            producto__pb2.ProductoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
